### ISSUE TITLE
The welcome screen crashes when the selected language is Arabic.

### ISSUE THREAD

**Issue by fathzer** [yapbam/yapbam#14]
The problem is the Arabic translation contains wrong translations that makes com.fathzer.jlocal.Formatter.format(String format, Object ... args) crash.

The underlying method that sends an IllegalArgumentException is java.text.MessageFormat.format(String pattern, Object ... arguments) because it encounters a wrong pattern (wrong pattern is something like "here is a <b>{0</b>} value" instead of "here is a <b>{0}</b> value").

We should add a new junit test in net.yapbam.gui.TranslationsTest to verify that all translations that contains valid MessageFormat pattern in the base resource file (for example Resources.properties), are valid (for Resources_it.properties, Resources_fr, and so on).

This test as well as the current test that detect missing translations in the base resource file is a generic useful test. Maybe there's already a library that does it. If not, maybe it could be a good idea to deliver a test library that tests that ...

**Comment by marcoM32** [comment]
I @fathzer , can you assaine tu me this issue? I will try to work on it in the afternoom.

**Comment by marcoM32** [comment]
Hi @fathzer, please see #15

**Comment by fathzer** [comment]
Fix released in 0.21.3
